package view;

public enum Type {
	WALKER,BLOCKER,TUNNELER,
	DIGGER,PARACHUTIST,CARPENTER,
	BOMBER,CLIMBER,
	SIMPLE_DESTRUCTIBLE,BOMB,AGAIN,
	SIMPLE_INDESTRUCTIBLE,LAVA,TP,
	START,END,
	VOID;
}
